// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fanx/dvm/ticket.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PubkeysChangeProposalPayload indicates data of public keys changes proposal
// ticket.
type PubkeysChangeProposalPayload struct {
	// public_keys contain new pub keys to be added to public keys.
	PublicKeys []string `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	// leader_index is the universal unique identifier of the public key.
	LeaderIndex uint32 `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (m *PubkeysChangeProposalPayload) Reset()         { *m = PubkeysChangeProposalPayload{} }
func (m *PubkeysChangeProposalPayload) String() string { return proto.CompactTextString(m) }
func (*PubkeysChangeProposalPayload) ProtoMessage()    {}
func (*PubkeysChangeProposalPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_1915d882665bb85f, []int{0}
}
func (m *PubkeysChangeProposalPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PubkeysChangeProposalPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PubkeysChangeProposalPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PubkeysChangeProposalPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubkeysChangeProposalPayload.Merge(m, src)
}
func (m *PubkeysChangeProposalPayload) XXX_Size() int {
	return m.Size()
}
func (m *PubkeysChangeProposalPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PubkeysChangeProposalPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PubkeysChangeProposalPayload proto.InternalMessageInfo

func (m *PubkeysChangeProposalPayload) GetPublicKeys() []string {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *PubkeysChangeProposalPayload) GetLeaderIndex() uint32 {
	if m != nil {
		return m.LeaderIndex
	}
	return 0
}

// ProposalVotePayload indicates vote data ticket.
type ProposalVotePayload struct {
	// proposal_id is the id of the proposal.
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// vote is the chosen option for the vote.
	Vote ProposalVote `protobuf:"varint,2,opt,name=vote,proto3,enum=fanx.dvm.ProposalVote" json:"vote,omitempty"`
}

func (m *ProposalVotePayload) Reset()         { *m = ProposalVotePayload{} }
func (m *ProposalVotePayload) String() string { return proto.CompactTextString(m) }
func (*ProposalVotePayload) ProtoMessage()    {}
func (*ProposalVotePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_1915d882665bb85f, []int{1}
}
func (m *ProposalVotePayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProposalVotePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProposalVotePayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProposalVotePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalVotePayload.Merge(m, src)
}
func (m *ProposalVotePayload) XXX_Size() int {
	return m.Size()
}
func (m *ProposalVotePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalVotePayload.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalVotePayload proto.InternalMessageInfo

func (m *ProposalVotePayload) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *ProposalVotePayload) GetVote() ProposalVote {
	if m != nil {
		return m.Vote
	}
	return ProposalVote_PROPOSAL_VOTE_UNSPECIFIED
}

func init() {
	proto.RegisterType((*PubkeysChangeProposalPayload)(nil), "fanx.dvm.PubkeysChangeProposalPayload")
	proto.RegisterType((*ProposalVotePayload)(nil), "fanx.dvm.ProposalVotePayload")
}

func init() { proto.RegisterFile("fanx/dvm/ticket.proto", fileDescriptor_1915d882665bb85f) }

var fileDescriptor_1915d882665bb85f = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x83, 0x30,
	0x1c, 0x87, 0xa9, 0x2e, 0x46, 0x3b, 0xf5, 0xc0, 0xa2, 0x21, 0xc6, 0x54, 0xdc, 0xc1, 0x10, 0x0f,
	0x90, 0xe8, 0x0b, 0x18, 0x3d, 0x2d, 0x5e, 0x08, 0x07, 0x0f, 0x5e, 0x48, 0x4b, 0xff, 0xdb, 0xc8,
	0x80, 0x36, 0xa5, 0x90, 0xf5, 0x2d, 0x7c, 0x2c, 0x8f, 0x3b, 0x7a, 0x34, 0xf0, 0x22, 0x06, 0x18,
	0x66, 0xd7, 0xaf, 0xbf, 0x7c, 0xe9, 0xff, 0xc3, 0x57, 0x4b, 0x5a, 0x6c, 0x03, 0x5e, 0xe7, 0x81,
	0x4e, 0x93, 0x0d, 0x68, 0x5f, 0x2a, 0xa1, 0x85, 0x7d, 0xda, 0x61, 0x9f, 0xd7, 0xf9, 0xcd, 0xec,
	0x7f, 0x50, 0x0b, 0x0d, 0xc3, 0xf3, 0x9c, 0xe1, 0xdb, 0xb0, 0x62, 0x1b, 0x30, 0xe5, 0xdb, 0x9a,
	0x16, 0x2b, 0x08, 0x95, 0x90, 0xa2, 0xa4, 0x59, 0x48, 0x4d, 0x26, 0x28, 0xb7, 0xef, 0xf0, 0x54,
	0x56, 0x2c, 0x4b, 0x93, 0xb8, 0xdb, 0x38, 0xc8, 0x3d, 0xf6, 0xce, 0x22, 0x3c, 0xa0, 0x77, 0x30,
	0xa5, 0x7d, 0x8f, 0xcf, 0x33, 0xa0, 0x1c, 0x54, 0x9c, 0x16, 0x1c, 0xb6, 0xce, 0x91, 0x8b, 0xbc,
	0x8b, 0x68, 0x3a, 0xb0, 0x45, 0x87, 0xe6, 0x0c, 0xcf, 0x46, 0xed, 0x87, 0xd0, 0x70, 0xa8, 0xde,
	0xe3, 0x38, 0xe5, 0x0e, 0x72, 0x91, 0x37, 0x89, 0xf0, 0x88, 0x16, 0xdc, 0x7e, 0xc4, 0x93, 0xee,
	0xa7, 0xbd, 0xf2, 0xf2, 0xe9, 0xda, 0x1f, 0x2f, 0xf1, 0x0f, 0x6d, 0x51, 0xbf, 0x79, 0x7d, 0xf9,
	0x6e, 0x08, 0xda, 0x35, 0x04, 0xfd, 0x36, 0x04, 0x7d, 0xb5, 0xc4, 0xda, 0xb5, 0xc4, 0xfa, 0x69,
	0x89, 0xf5, 0xf9, 0xb0, 0x4a, 0xf5, 0xba, 0x62, 0x7e, 0x22, 0xf2, 0x40, 0x66, 0xd4, 0x80, 0x5a,
	0x56, 0xca, 0x04, 0x7d, 0x8c, 0x7d, 0x2f, 0x23, 0xa1, 0x64, 0x27, 0x7d, 0x90, 0xe7, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0x88, 0x3f, 0xc5, 0x48, 0x01, 0x00, 0x00,
}

func (m *PubkeysChangeProposalPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PubkeysChangeProposalPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PubkeysChangeProposalPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LeaderIndex != 0 {
		i = encodeVarintTicket(dAtA, i, uint64(m.LeaderIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PublicKeys) > 0 {
		for iNdEx := len(m.PublicKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PublicKeys[iNdEx])
			copy(dAtA[i:], m.PublicKeys[iNdEx])
			i = encodeVarintTicket(dAtA, i, uint64(len(m.PublicKeys[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProposalVotePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProposalVotePayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProposalVotePayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Vote != 0 {
		i = encodeVarintTicket(dAtA, i, uint64(m.Vote))
		i--
		dAtA[i] = 0x10
	}
	if m.ProposalId != 0 {
		i = encodeVarintTicket(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTicket(dAtA []byte, offset int, v uint64) int {
	offset -= sovTicket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PubkeysChangeProposalPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PublicKeys) > 0 {
		for _, s := range m.PublicKeys {
			l = len(s)
			n += 1 + l + sovTicket(uint64(l))
		}
	}
	if m.LeaderIndex != 0 {
		n += 1 + sovTicket(uint64(m.LeaderIndex))
	}
	return n
}

func (m *ProposalVotePayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovTicket(uint64(m.ProposalId))
	}
	if m.Vote != 0 {
		n += 1 + sovTicket(uint64(m.Vote))
	}
	return n
}

func sovTicket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTicket(x uint64) (n int) {
	return sovTicket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PubkeysChangeProposalPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PubkeysChangeProposalPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PubkeysChangeProposalPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeys = append(m.PublicKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderIndex", wireType)
			}
			m.LeaderIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTicket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProposalVotePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProposalVotePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProposalVotePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vote", wireType)
			}
			m.Vote = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vote |= ProposalVote(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTicket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTicket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTicket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTicket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTicket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTicket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTicket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTicket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTicket = fmt.Errorf("proto: unexpected end of group")
)
