// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fanx/dvm/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the dvm module's genesis state.
type GenesisState struct {
	// params contains parameters of dvm module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// key_vault trusted keys from genesis file.
	KeyVault KeyVault `protobuf:"bytes,2,opt,name=key_vault,json=keyVault,proto3" json:"key_vault"`
	// pubkeys_change_proposals is the finished proposal list for the
	// public keys change.
	PubkeysChangeProposals []PublicKeysChangeProposal `protobuf:"bytes,3,rep,name=pubkeys_change_proposals,json=pubkeysChangeProposals,proto3" json:"pubkeys_change_proposals"`
	// proposal_stats holds the proposal statistics.
	ProposalStats ProposalStats `protobuf:"bytes,4,opt,name=proposal_stats,json=proposalStats,proto3" json:"proposal_stats"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a70a5ba85e4117, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetKeyVault() KeyVault {
	if m != nil {
		return m.KeyVault
	}
	return KeyVault{}
}

func (m *GenesisState) GetPubkeysChangeProposals() []PublicKeysChangeProposal {
	if m != nil {
		return m.PubkeysChangeProposals
	}
	return nil
}

func (m *GenesisState) GetProposalStats() ProposalStats {
	if m != nil {
		return m.ProposalStats
	}
	return ProposalStats{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "fanx.dvm.GenesisState")
}

func init() { proto.RegisterFile("fanx/dvm/genesis.proto", fileDescriptor_06a70a5ba85e4117) }

var fileDescriptor_06a70a5ba85e4117 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0xc6, 0x37, 0x20, 0x04, 0x8b, 0x1a, 0xd3, 0x20, 0x34, 0x1c, 0x2a, 0xe1, 0x60, 0x38, 0x75,
	0x09, 0xc6, 0xbb, 0x51, 0x13, 0x0f, 0x5c, 0x88, 0x26, 0x1e, 0xbc, 0x2c, 0x1d, 0x94, 0x41, 0xd8,
	0x68, 0xb3, 0x76, 0xc4, 0xbe, 0x85, 0x6f, 0xe0, 0xeb, 0x70, 0xe4, 0xe8, 0xc9, 0x18, 0x78, 0x11,
	0xb3, 0xae, 0x1b, 0x70, 0xdb, 0xbe, 0xdf, 0xff, 0xfb, 0xfa, 0xfd, 0xff, 0xa0, 0x3d, 0xa3, 0xab,
	0x4f, 0x6f, 0xba, 0x8e, 0xbd, 0x90, 0xad, 0x98, 0x5c, 0x48, 0x22, 0x12, 0xae, 0x38, 0x6c, 0x64,
	0x3a, 0x99, 0xae, 0xe3, 0x6e, 0x2b, 0xe4, 0x21, 0x37, 0xa2, 0x97, 0x7d, 0xe5, 0xbc, 0x7b, 0x5d,
	0xfa, 0x04, 0x4d, 0x68, 0x6c, 0x6d, 0x5d, 0x54, 0xca, 0x4b, 0xa6, 0xfd, 0x35, 0x4d, 0x23, 0x65,
	0x49, 0xe7, 0x60, 0x48, 0xb8, 0xe0, 0x92, 0x46, 0x16, 0xb4, 0x4a, 0x20, 0x15, 0x55, 0x36, 0xa8,
	0xff, 0x5d, 0x01, 0xe7, 0x2f, 0x79, 0xa3, 0x37, 0x45, 0x15, 0x83, 0x04, 0xd4, 0xf3, 0x97, 0x90,
	0xdb, 0x73, 0x07, 0xcd, 0xe1, 0x15, 0x29, 0x1a, 0x92, 0xb1, 0xd1, 0x1f, 0x6b, 0x9b, 0xdf, 0x1b,
	0xe7, 0xd5, 0x4e, 0xc1, 0x7b, 0x70, 0x56, 0x56, 0x40, 0x15, 0x63, 0x81, 0x07, 0xcb, 0x88, 0xe9,
	0xf7, 0x8c, 0x58, 0x53, 0x63, 0x69, 0xff, 0x61, 0x00, 0x90, 0x48, 0x83, 0x25, 0xd3, 0xd2, 0x9f,
	0xcc, 0xe9, 0x2a, 0x64, 0x7e, 0x51, 0x57, 0xa2, 0x6a, 0xaf, 0x3a, 0x68, 0x0e, 0xfb, 0x47, 0x0f,
	0xa7, 0x41, 0xb4, 0x98, 0x8c, 0x98, 0x96, 0x4f, 0x66, 0x76, 0x6c, 0x47, 0x6d, 0x6a, 0xdb, 0x26,
	0x9d, 0x42, 0x09, 0x9f, 0xc1, 0x65, 0x11, 0xea, 0x9b, 0x9d, 0x51, 0xcd, 0xf4, 0xeb, 0x1c, 0x25,
	0x5b, 0x9e, 0xed, 0x5e, 0x6c, 0x76, 0x21, 0x4e, 0xc4, 0x87, 0xcd, 0x0e, 0xbb, 0xdb, 0x1d, 0x76,
	0xff, 0x76, 0xd8, 0xfd, 0xda, 0x63, 0x67, 0xbb, 0xc7, 0xce, 0xcf, 0x1e, 0x3b, 0x1f, 0xb7, 0xe1,
	0x42, 0xcd, 0xd3, 0x80, 0x4c, 0x78, 0xec, 0x89, 0x88, 0x6a, 0x96, 0xcc, 0xd2, 0x44, 0x7b, 0xe6,
	0xce, 0xf9, 0xa5, 0x95, 0x16, 0x4c, 0x06, 0x75, 0x73, 0xea, 0xbb, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0xb8, 0xae, 0xce, 0x04, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ProposalStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.PubkeysChangeProposals) > 0 {
		for iNdEx := len(m.PubkeysChangeProposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PubkeysChangeProposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.KeyVault.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.KeyVault.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PubkeysChangeProposals) > 0 {
		for _, e := range m.PubkeysChangeProposals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.ProposalStats.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyVault", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.KeyVault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubkeysChangeProposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubkeysChangeProposals = append(m.PubkeysChangeProposals, PublicKeysChangeProposal{})
			if err := m.PubkeysChangeProposals[len(m.PubkeysChangeProposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProposalStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
