// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fanx/mint/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params define the parameters for the module.
type Params struct {
	// mint_denom is the type of coin to mint.
	MintDenom string `protobuf:"bytes,1,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	// blocks_per_year is expected blocks per year.
	BlocksPerYear int64 `protobuf:"varint,2,opt,name=blocks_per_year,json=blocksPerYear,proto3" json:"blocks_per_year,omitempty" yaml:"blocks_per_year"`
	// phases contains phases of inflation.
	Phases []Phase `protobuf:"bytes,3,rep,name=phases,proto3" json:"phases" yaml:"phases"`
	// exclude_amount is the excluded amount form being calculated in inflation.
	ExcludeAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=exclude_amount,json=excludeAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"exclude_amount" yaml:"exclude_amount"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf914a113296e64e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *Params) GetBlocksPerYear() int64 {
	if m != nil {
		return m.BlocksPerYear
	}
	return 0
}

func (m *Params) GetPhases() []Phase {
	if m != nil {
		return m.Phases
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "fanx.mint.Params")
}

func init() { proto.RegisterFile("fanx/mint/params.proto", fileDescriptor_cf914a113296e64e) }

var fileDescriptor_cf914a113296e64e = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0x93, 0xb6, 0x14, 0x7a, 0x52, 0x95, 0x60, 0x4b, 0x28, 0x98, 0x94, 0x0c, 0xda, 0xc5,
	0x04, 0x74, 0xeb, 0x22, 0x0d, 0x82, 0xb8, 0x95, 0x6c, 0xba, 0x84, 0x6b, 0x7a, 0xfd, 0x43, 0x73,
	0x77, 0xe1, 0xee, 0x02, 0xcd, 0xb7, 0x70, 0x74, 0x14, 0x3f, 0x4d, 0xc7, 0x8e, 0xe2, 0x10, 0xa4,
	0xfd, 0x06, 0xfd, 0x04, 0x72, 0x77, 0x41, 0xaa, 0x53, 0x72, 0xbf, 0xf7, 0x7d, 0x9e, 0xe7, 0xe5,
	0x01, 0xdd, 0x19, 0x24, 0xeb, 0x00, 0x2f, 0x89, 0x08, 0x32, 0xc8, 0x20, 0xe6, 0x7e, 0xc6, 0xa8,
	0xa0, 0x56, 0x4b, 0x72, 0x5f, 0xf2, 0xde, 0xc5, 0x9c, 0xce, 0xa9, 0xa2, 0x81, 0xfc, 0xd3, 0x0b,
	0xbd, 0xce, 0x91, 0x70, 0x01, 0x39, 0xd2, 0xd8, 0xfb, 0xa8, 0x81, 0xe6, 0x58, 0x19, 0x59, 0x97,
	0x00, 0xc8, 0x71, 0x3c, 0x45, 0x84, 0x62, 0xdb, 0xec, 0x9b, 0x83, 0x56, 0xd4, 0x92, 0xe4, 0x41,
	0x02, 0x2b, 0x04, 0x67, 0x93, 0x94, 0x26, 0x2b, 0x1e, 0x67, 0x88, 0xc5, 0x05, 0x82, 0xcc, 0xae,
	0xf5, 0xcd, 0x41, 0x3d, 0xec, 0x1d, 0x4a, 0xb7, 0x5b, 0x40, 0x9c, 0x0e, 0xbd, 0x7f, 0x0b, 0x5e,
	0xd4, 0xd6, 0x64, 0x8c, 0xd8, 0x33, 0x82, 0xcc, 0xba, 0x07, 0x4d, 0x15, 0xce, 0xed, 0x7a, 0xbf,
	0x3e, 0x38, 0xb9, 0x3d, 0xf7, 0x7f, 0xcf, 0xf6, 0xc7, 0x72, 0x10, 0x76, 0x36, 0xa5, 0x6b, 0x1c,
	0x4a, 0xb7, 0xad, 0x0d, 0xf5, 0xb6, 0x17, 0x55, 0x32, 0x8b, 0x80, 0x53, 0xb4, 0x4e, 0xd2, 0x7c,
	0x8a, 0x62, 0x88, 0x69, 0x4e, 0x84, 0xdd, 0x90, 0x77, 0x86, 0x8f, 0x52, 0xf6, 0x55, 0xba, 0x57,
	0xf3, 0xa5, 0x58, 0xe4, 0x13, 0x3f, 0xa1, 0x38, 0x48, 0x28, 0xc7, 0x94, 0x57, 0x9f, 0x1b, 0x3e,
	0x5d, 0x05, 0xa2, 0xc8, 0x10, 0xf7, 0x9f, 0x88, 0x38, 0x94, 0x6e, 0x47, 0x07, 0xfc, 0x75, 0xf3,
	0xa2, 0x76, 0x05, 0x46, 0xea, 0x3d, 0x6c, 0xbc, 0xbd, 0xbb, 0x46, 0x38, 0xda, 0xec, 0x1c, 0x73,
	0xbb, 0x73, 0xcc, 0xef, 0x9d, 0x63, 0xbe, 0xee, 0x1d, 0x63, 0xbb, 0x77, 0x8c, 0xcf, 0xbd, 0x63,
	0xbc, 0x5c, 0x1f, 0xe5, 0x65, 0x29, 0x2c, 0x10, 0x9b, 0xe5, 0xac, 0x08, 0x54, 0xd7, 0x55, 0xdb,
	0x2a, 0x74, 0xd2, 0x54, 0x75, 0xdf, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xac, 0xbe, 0x36,
	0xc0, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExcludeAmount.Size()
		i -= size
		if _, err := m.ExcludeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Phases) > 0 {
		for iNdEx := len(m.Phases) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Phases[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.BlocksPerYear != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlocksPerYear))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MintDenom) > 0 {
		i -= len(m.MintDenom)
		copy(dAtA[i:], m.MintDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MintDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.BlocksPerYear != 0 {
		n += 1 + sovParams(uint64(m.BlocksPerYear))
	}
	if len(m.Phases) > 0 {
		for _, e := range m.Phases {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.ExcludeAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerYear", wireType)
			}
			m.BlocksPerYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerYear |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phases", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phases = append(m.Phases, Phase{})
			if err := m.Phases[len(m.Phases)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcludeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExcludeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
